cart/urls.py
from django.urls import path
from . import views
from ajax_select import urls as ajax_select_urls


app_name = "cart"

urlpatterns = [
    path('show/', views.show_cart, name='show_cart'),
    path('add/<slug:item_slug>/', views.cart_add_item, name='cart_add_item'),
    path('remove/<slug:item_slug>/', views.cart_remove_item, name='cart_remove_item'),
    path('check_out/', views.check_out_line, name='cart_checking')
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddItemForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="Количество")
    update = forms.BooleanField(required=False,initial=False)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from item.models import Item
from .cart import Cart
from .forms import CartAddItemForm
from django.core.serializers import serialize
from django.http import HttpResponse, HttpResponseRedirect


@require_POST
def cart_add_item(request, item_slug):
    cart = Cart(request)
    print(request.POST)
    item = get_object_or_404(Item, slug=item_slug)
    form = CartAddItemForm(request.POST)
    if form.is_valid():
        print("cart adding form is valid")
        cd = form.cleaned_data
        cart.add(item=item, quantity=cd["quantity"], update_quantity=cd['update'])


    return redirect("cart:show_cart")

@require_POST
def cart_remove_item(request, item_slug):
    print(request.POST)
    cart = Cart(request)
    item = get_object_or_404(Item, slug=item_slug)
    cart.remove(item)
    return HttpResponse(cart.get_total_price())
        # redirect("cart:show_cart")


def show_cart(request):
    cart = Cart(request)
    return render(request, "cart_content.html", {"cart": cart})



def check_out_line(request):
    cart = Cart(request)
    if not len(cart):
        return HttpResponseRedirect("/new_test")

    return render(request, 'сheckout.html',locals())

cart/templates/cart_content.html
{% extends "cart_modal.html" %}
{% block cart_content %}
    {% for item in cart %}
        {% with good=item.item %}
            <div class="row mb-3">
                <div class="col-6" data-th="Product">
                    <a href="{{ good.get_absolute_url }}"> </a>
                    <div class="row">
                        <div class="col-lg-4"><img src="http://placehold.it/100x100" alt="..."
                                                   class="img-responsive"/></div>
                        <div class="col-lg-7">
                            <h5 class="nomargin"><a href="{{ good.get_absolute_url }}">{{ good.title }}</a></h5>

                        </div>
                    </div>
                </div>

                <div class="col-2 text-right" data-url="{% url "cart:cart_add_item" good.slug %}" data-th="Quantity">
                    <input type="number" min="1" class="itemQuant form-control text-center" value="{{ item.quantity }}">
                </div>


                <div class="col-2 text-right" data-th="Price">
                    <div><h5> {{ item.total_price|floatformat }} </h5></div>
                </div>

                <form class="cartRemove" action="{% url "cart:cart_remove_item" good.slug %}" method="post">
                    {% csrf_token %}
                    <div class="col-2 text-right" data-th="">
                        <button class="btn btn-danger"><i class="fa fa-trash-alt"></i></button>
                    </div>
                </form>
            </div>
        {% endwith %}
    {% endfor %}

{% endblock %}

cart/templates/cart_modal.html
<style>

    td.my-td {
        border: none;

    }

    tr.my-tr th {
        border-top: none;
        border-bottom: none;

    }

</style>

<div class="modal-body">


    <div class="container">
        {% block cart_content %}
        {% endblock %}

    </div>

    <hr class="before-it">
    <div class="row pt-4">

        <div class="float-left col-4"><a href="#" data-dismiss="modal" class="goon btn btn-warning"><i class=""></i>Продолжить</a>
        </div>

        <div class="col-4"><strong> Общая сумма: <div class="full_amount d-inline">{{ cart.get_total_price|floatformat }}</div> </strong></div>
        {% if not cart.is_empty %}
            <div class="col-4"><a href="{% url "cart:cart_checking" %}" class="disabled btn btn-success">Перейти к
                оформлению
                <i class=""></i></a></div>
        {% else %}
            <div class="col-4"><a href="{% url "cart:cart_checking" %}" class="btn btn-success">Перейти к
                оформлению
                <i class=""></i></a></div>
        {% endif %}
    </div>
</div>