cart/urls.py
from django.urls import path
from . import views
from ajax_select import urls as ajax_select_urls


app_name = "cart"

urlpatterns = [
    path('show/', views.show_cart, name='show_cart'),
    path('add/<slug:item_slug>/', views.cart_add_item, name='cart_add_item'),
    path('remove/<slug:item_slug>/', views.cart_remove_item, name='cart_remove_item'),
    path('check_out/', views.check_out_line, name='cart_checking')
]

item/urls.py
from django.urls import path
from . import views

app_name = "item"

urlpatterns = [
    path('new_test/<category>/<slug:item_slug>/', views.item, name='item_main'),
    path(r'details/', views.details, name='details'),
]

item/models.py
import hashlib
import time
import uuid

from django.core.validators import MinValueValidator
from django.db import models
from django.db import transaction
from django.db.models.signals import post_save
from django.urls import reverse

from category.models import Category
from customer.models import Customer
from st_app.models import Brand, CommonFields
from translates_word import categories


def _createHash():
    hash = hashlib.sha1()
    hash.update(str(time.time()).encode("ascii"))
    return hash.hexdigest()[:10]

class ItemFieldTypeValue(models.Model):
    field_type_id = models.AutoField(primary_key=True, unique=True)
    # field_type = models.CharField(max_length=100, null=True, blank=True, default=None)
    field_value = models.CharField(max_length=100, unique=True)
    unique_str_id = models.CharField(max_length=10, editable=False)

    def __str__(self):
        return "{0}".format(self.field_value)

    def __repr__(self):
        return "{0}".format(self.field_value)

    def save(self, *args, **kwargs):
        super(ItemFieldTypeValue, self).save(*args, **kwargs)


class ItemFieldTitle(models.Model):
    field_title_value_id = models.AutoField(primary_key=True, unique=True)
    field_title = models.CharField(max_length=100, unique=True)
    use_for = models.CharField(max_length=50, default=None, blank=True)

    def __str__(self):
        return "{0}".format(self.field_title)


class ItemField(models.Model):
    field_id = models.AutoField(primary_key=True, unique=True)
    # type = models.ForeignKey(ItemFieldTypeValue, max_length=100, null=True, blank=True)
    value = models.ForeignKey(ItemFieldTypeValue, max_length=100, default=None, on_delete=models.CASCADE)
    title = models.ForeignKey(ItemFieldTitle, max_length=100, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return "{0}-{1}".format(self.title, self.value)

    class Meta:
        unique_together = ['value', 'title']
        db_table = "ItemField"
        verbose_name_plural = "ItemField"


class Item(CommonFields):
    class Meta:
        db_table = "Item"
        verbose_name_plural = "Item"

    item_price = models.DecimalField(max_digits=10, decimal_places=3, default=0,
                                     validators=[MinValueValidator(0, "Price must be positive number!")])
    item_quantity = models.PositiveIntegerField(default=0,
                                                validators=[MinValueValidator(0, "Quantity must be positive number!")])

    item_short_desc = models.CharField(max_length=200, default=None, blank=True)
    item_category = models.ForeignKey(Category, default=None, blank=True, null=True, on_delete=models.CASCADE)
    item_create_date = models.DateTimeField(auto_now_add=True, null=True)
    item_update_date = models.DateTimeField(auto_now=True)
    item_published = models.BooleanField(default=False)
    item_metadata = models.CharField(max_length=500, default=None, blank=True)
    item_brand = models.ForeignKey(Brand, default=None, blank=True, null=True, on_delete=models.CASCADE)
    item_fields = models.ManyToManyField(ItemField, through='ItemFieldItem')
    slug = models.SlugField(max_length=60, default=None)
    main_image = models.CharField(max_length=500,blank=True, default=None)




    def get_absolute_url(self):

        return reverse('item:item_main', args=[categories[str(self.item_category).lower()], self.slug])

    def __str__(self):
        return self.title


import os


def get_image_path(instance, filename):
    part_number = ItemField.objects.filter(title__field_title="part_number",item__id=instance.item.id)\
        .values_list("value__field_value")[0]
    return os.path.join('item/static/photos', "_".join(instance.item.title.split()) +"_"+part_number[0], filename)

class ItemImage(models.Model):
    image_id = models.AutoField(primary_key=True, unique=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_image_path, blank=True, default=None)
    image_type = models.PositiveIntegerField(default=0)
    as_main = models.BooleanField(default=False)



    class Meta:
        db_table = "ItemImage"
        verbose_name_plural = "ItemImage"
        # instance.image = models.ImageField(upload_to=str(instance.image).split("/", 2)[2],blank=True,default=None)

@transaction.atomic()
def static_url(sender, instance, **kwargs):

    if kwargs["created"]:
        instance.image = str(instance.image).split("/", 2)[2]
        instance.save(force_update=True)
    if instance.as_main:
        instance.item.main_image = instance.image
        instance.item.save(force_update=True)


post_save.connect(static_url, sender=ItemImage)



class ItemFieldItem(models.Model):
    class Meta:
        db_table = "ItemFieldItem"
        unique_together = (("item", "item_field"),)

    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    item_field = models.ForeignKey(ItemField, on_delete=models.CASCADE)
    use_as_customer_filter = models.BooleanField(default=False)
    use_as_common_detail = models.BooleanField(default=False)

    def __str__(self):
        return "{0}".format(self.item_field)

        # default = uuid.uuid4().hex[:6].lower( default=uuid.uuid4().hex[:6].lower())


def set_unique(sender, instance, **kwargs):
    if kwargs["created"]:
        instance.unique_str_id = uuid.uuid4().hex[:6].lower()
        instance.save(force_update=True)


post_save.connect(set_unique, sender=ItemFieldTypeValue)

# class ItemComment(CommonFields):
#     item = models.ForeignKey(Item, on_delete=models.CASCADE)
#     date_time = models.DateTimeField(auto_now_add=True)
#     customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
#     rating = models.SmallIntegerField(default=0)

item/views.py
from django.shortcuts import render

import translates_word

from .models import Item, ItemFieldItem, ItemField


# def show_item_processor(request):
#     q = Q()
#     if request.GET:
#         q = Q(item_fields__value__field_value=request.GET.get("series"))
#
#     processors = Item.objects.filter(item_category__title="процессоры").filter(q)
#
#     return render(request, 'processor.html', {"p": processors}, locals())
#


def item(request, category, item_slug):
    title = translates_word.reversed_categories[category]
    self_item = Item.objects.filter(item_category__title=title).get(slug=item_slug)
    title_detail = ItemField.objects.filter(item__id=self_item.id,title__use_for="title").values_list("value__field_value")
    title_detail = " / ".join(i[0] for i in title_detail)
    #
    # for image in self_item.itemimage_set.all():
    #     print(type(str(image.image)))

    # values_list(
    #     "item_field__value__field_value", "item_field__value__field_type")

    common_details = ItemFieldItem.objects.filter(item__slug=item_slug, use_as_common_detail=True).values_list(
        "item_field__title__field_title", "item_field__value__field_value")

    # warranty = self_item.item_fields.get(title__field_title="warranty")
    if request.method == "POST":
        return render(request, "item_content.html", locals())
    return render(request, 'item_main_template.html', locals())


def details(request):
    print(request.POST)
    full_details = ItemFieldItem.objects.filter(item__slug=request.POST.get("item_slug")).values_list(
        "item_field__title__field_title",
        "item_field__value__field_value")

    words = translates_word.values
    print(full_details)
    return render(request, "item_full_details.html", locals())


#
# @login_required(login_url="/signup/")
# def add_comment(request):
#     if request.POST:
#         form = NewCommentValid(request.POST)
#         if form.is_valid():
#             Comment.objects.create(about=Item.objects.get(id=int(form.data.get("item"))),
#                                    author=User.objects.get(email=form.data.get("email")), text=form.data.get("comment"))
#         else:
#             print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
#     return HttpResponseRedirect(request.path.rsplit("/", 2)[0])
#
#





def show_items(request, category):
    Item.objects.filter()
    pass


def show_filters(request, category):
    any_item = Item.objects.filter(item_category=category).first()

item/templates/common_details.html
{% load for_human_reading %}

<div class="col-lg-4">
    <table class="table mt-5 ml-5 table-borderless">
    <div style="">
        {% for detail in common_details %}
            <tbody>
{#            {% if detail.2 %}#}
{#            <tr>#}
{#                <td class="no-gutters text-secondary h6 text-right">#}
{#                    <div class="float-left">{{ detail.0|for_human_reading|capfirst }}: </div>#}
{#                    <div class="float-right">{{ detail.1 }} {{ detail.2 }}</div></td>#}
{##}
{#            </tr>#}
{#            {% else %}#}
            <tr>
                <td class="no-gutters text-secondary h6 text-right">
                    <div class="float-left">{{ detail.0|for_human_reading|capfirst }}:</div>
                    <div class="float-right"><div class="text-left" style="display:block;">{{ detail.1 }}</div></div>
                </td>

            </tr>
{#            {% endif %}#}
        {% endfor %}

        </tbody>
    </div>
    </table>
</div>

item/templates/item_common_details.html
{% load for_human_reading %}

<div class="col-lg-4">
    <table class="table mt-5 ml-5 table-borderless">
    <div style="">
        {% for detail in common_details %}
            <tbody>
{#            {% if detail.2 %}#}
{#            <tr>#}
{#                <td class="no-gutters text-secondary h6 text-right">#}
{#                    <div class="float-left">{{ detail.0|for_human_reading|capfirst }}: </div>#}
{#                    <div class="float-right">{{ detail.1 }} {{ detail.2 }}</div></td>#}
{##}
{#            </tr>#}
{#            {% else %}#}
            <tr>
                <td class="no-gutters text-secondary h6 text-right">
                    <div class="float-left">{{ detail.0|for_human_reading|capfirst }}:</div>
                    <div class="float-right"><div class="text-left" style="display:block;">{{ detail.1 }}</div></div>
                </td>

            </tr>
{#            {% endif %}#}
        {% endfor %}

        </tbody>
    </div>
    </table>
</div>

item/templates/item_content.html
{#<div class="row">#}
{% load for_human_reading static make_str %}

<script>


    $(document).on("click", "#buy-" + "{{ item_slug }}", function (event) {
        event.preventDefault();
        send_with_ajax($("#item-{{ item_slug }}").serializeArray(), "{% url 'cart:cart_add_item' item_slug %}", function (response) {
            var $container = jQuery(".cart-content");

            $container.html(response);
            $("#cartModal").modal();

        });

    });
</script>


<main class="card">
    <div class="row no-gutters">
        <aside class="col-sm-5 border-right">
            <article class="gallery-wrap  mt-2">
                <div class="img-big-wrap">
                    <div><a href="images/items/1.jpg" data-fancybox=""><img src="{% static self_item.main_image %}"></a>
                    </div>
                </div> <!-- slider-product.// -->
                <div class="img-small-wrap">
                    {% for image in self_item.itemimage_set.all %}
                        {% with image.image|make_str as str_img_path %}
                            {% ifnotequal self_item.main_image str_img_path %}
                                <div class="item-gallery"><img src="{% static str_img_path %}"></div>
                            {% endifnotequal %}
                        {% endwith %}
                    {% endfor %}
                </div> <!-- slider-nav.// -->
            </article> <!-- gallery-wrap .end// -->
        </aside>
        <aside class="col-sm-7">
            <article class="card-body">
                <!-- short-info-wrap -->
                <h3 class="item-title title mb-3">
                    {{ self_item.title }} /
                    {{ title_detail }}
                </h3>

                <div class="mb-5 mt-5">
                        <span class="btn num btn-outline-success disabled btn-lg">{{ self_item.item_price|floatformat }} <span
                                class="currency"> грн </span></span>
                    <button href="#" id="buy-{{ item_slug }}" form="item-{{ item_slug }}"
                            class="btn btn-lg  btn-success  ml-4"> Купить
                    </button>

                    <div class="form">
                        {#                       #}
                        <form id="item-{{ item_slug }}" action="{% url "cart:cart_add_item" item_slug %}"
                              method="POST">{% csrf_token %}
                            <input type="hidden" name="quantity" min="1" value="1">
                            <input type="hidden" name="update" value="True">
                            {#                            onclick="document.forms['unit-{{ id }}'].submit()"#}
                        </form>
                    </div>
                </div> <!-- price-detail-wrap .// -->
                <hr>

                <div class="info mt-5 в-">
                    <div class="delivery h6">
                        <div class="mb-3"><b>Доставка</b> в <a href="#">Выбрать город</a></div>
                        <p>Самовывоз Новая почта - 50 грн. </p>
                        <p>Курьер Мист экспресс - 50 грн. </p>
                        <p>Курьер Новая почта (только безналичный расчет и оплата картой) - 50 грн. </p>

                    </div>
                    <hr>
                    <div class="check h6">
                        <p><b>Оплата</b> Наличными, Visa/MasterCard, Приват24, Кредит, Оплата частями, Мгновенная
                            рассрочка, Безналичными</p>

                    </div>
                    <hr>
                    <div class="check h6">
                        <p><b>Гарантия</b> 36 месяцев, обмен/возврат товара в течение 14 дней</p>
                    </div>
                    <hr>
                </div>
                <!-- short-info-wrap .// -->
            </article><!-- card-body.// -->
        </aside> <!-- col.// -->
    </div> <!-- row.// -->
</main> <!-- card.// -->
<article class="mt-3">

    <div class="row no-gutters justify-content-between">
        <div class="card mb-3 mr-5 col-lg-5 border-0">
            <div class="card-body">
                <h4>Описание товара</h4>
                <div class="mt-3">
                    {{ self_item.description|safe }}
                </div>
            </div> <!-- card-body.// -->

        </div>
        <div class="card mb-3  col-lg-6 border-0">
            <div class="card-body">
                <script>

                    send_with_ajax("", "/comments/show/{{ item_slug }}", function (response) {
                        console.log("comments is recieved")
                        $(".main-comments").html(response);
                    }, "GET");


                </script>
                <h4>Отзывы покупателей</h4>
                <div class="ml-3 mt-3 main-comments">


                </div>
            </div> <!-- card-body.// -->
        </div>
    </div>

    <div class="card">
        <div class="card-body col-lg-6">
            <h4>Краткие характеристики</h4>
            <div class="ml-3 mt-3">
                {% for detail in common_details %}

                    <div class="row">
                        <div class="text-secondary h6 ">{{ detail.0|for_human_reading|capfirst }}: <p></p></div>

                        <div class="h6  text-left">{{ detail.1 }}</div>
                    </div>
                {% endfor %}

            </div>
        </div> <!-- card-body.// -->
    </div>
</article>

item/templates/item_full_details.html
{% load for_human_reading %}

<div class="col-lg-4">
    <table class="table mt-5 table-borderless">
    <div style="">
        {% for detail in full_details %}
            <tbody>
            {% if detail.2 %}
            <tr>
                <td class="no-gutters text-secondary h6 text-right">
                    <div class="float-left">{{ detail.0|for_human_reading|capfirst }}: </div>
                    <div class="float-right">{{ detail.1 }} {{ detail.2 }}</div></td>

            </tr>
            {% else %}
            <tr>
                <td class="no-gutters text-secondary h6 text-right">
                    <div class="float-left">{{ detail.0|for_human_reading|capfirst }}:</div>
                    <div class="float-right"><div class="text-left" style="display:block;">
                        {%  if detail.1 in words %}
                            {{ detail.1|for_human_reading:"values" }}
                        {% else %}
                            {{ detail.1 }}
                        {% endif %}
                        </div></div>
                </td>

            </tr>
            {% endif %}
        {% endfor %}

        </tbody>
    </div>
    </table>
</div>

item/templates/item_main_template.html
{% extends "some_category_page.html" %}

{% block page_title %}
    {{ self_item.title }} /
    {{ title_detail }}
{% endblock %}

{% load django_bootstrap_breadcrumbs %}
{##}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb self_item "item.views.item" category item_slug %}
{% endblock %}


{% block content %}

    <div class="container">
        <script>

            function some_about_item(some, url) {
                $(document).on("click", "a[href='#" + some + "']", function (event) {
                    $(event.target).parent().children(".my-active").removeClass("my-active");
                    $(event.target).addClass("my-active");

                    var data = {"csrfmiddlewaretoken": csrftoken, "item_slug": "{{item_slug}}"};
                    send_with_ajax(data, url, function (response) {
                        $(".i-content-info").html(response);
                    });


                });
            }

            some_about_item("item_details", "{% url "item:details" %}");
            some_about_item("item_main", "{% url "item:item_main" category item_slug %}");


            $(document).on("click", ".show-comments", function (event) {
                {#                event.preventDefault();#}
                console.log("click on .show-comments");
                $(event.target).parent().children(".my-active").removeClass("my-active");
                $(event.target).addClass("my-active");


                send_with_ajax("", "/comments/show/" + $(event.target).data("href"), function (response) {

                    $(".i-content-info").html(response);
                }, "GET");
            });


            $(document).on("click", ".delivery-info", function (event) {
                $(event.target).parent().children(".my-active").removeClass("my-active");
                $(event.target).addClass("my-active");

                $(".i-content-info").html("<h5>Подробная информация о доставке товара</h5>");
            });

            $(document).on("click", ".warranty-info", function (event) {
                $(event.target).parent().children(".my-active").removeClass("my-active");
                $(event.target).addClass("my-active");

                $(".i-content-info").html("<h5>Подробная информация о гарантии на товар</h5>");

            });

            $(document).on("click", ".pay-info", function (event) {
                $(event.target).parent().children(".my-active").removeClass("my-active");
                $(event.target).addClass("my-active");

                $(".i-content-info").html("<h5>Подробная информация о способах оплаты товара</h5>");

            });

            $(window).load(function () {
                s = location.search;
                var href = location.href;
                var new_url = href.substring(0, href.indexOf('?'));
                window.history.pushState("", "", new_url);
                if (s != '') {
                    console.log(new_url);
                    var split = s.split('?');
                    var cat = split[1];
                    console.log(cat);
                    $('.show-' + cat).click();
                }
            });
        </script>


        <div class="card card-item mb-3 item-nav">

            <nav class="nav nav-pills nav-justified pl-1 pb-1" style="font-size: 14px;">
                <a id="unit-{{ id }}" class="nav-link my-active" href="#item_main">Все о товаре</a>
                <a id="details-{{ id }}" class="nav-link" href="#item_details">Характеристики</a>
                <a class="nav-link show-comments" href="#comments" data-href="{{ item_slug }}">Отзывы</a>
                <a id="delivery-{{ id }}" class="nav-link delivery-info" href="#">Доставка</a>
                <a id="delivery-{{ id }}" class="nav-link warranty-info" href="#">Гарантия</a>
                <a id="delivery-{{ id }}" class="nav-link pay-info" href="#">Оплата</a>
            </nav>

        </div>
        <div class="i-content-info">
            {% include "item_content.html" %}

        </div>
    </div>
    {#        {% include "comments.html" %}#}
{% endblock %}